version: '3.8'

services:
  go-web-demo-server2:
#    depends_on:
#      - mysql
    build:
      # 使用 context 指令指定 Dockerfile.bak 所在文件夹的路径
      context: .
      dockerfile: Dockerfile
    container_name: order
    env_file: .env
    ports:
      - 8082:8082
    restart: unless-stopped

networks:
  go-web-demo-net:
    # 声明这个网络是外部定义的
    external: true

#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    restart: unless-stopped
#    env_file: .env
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root # root用户的密码
#      MYSQL_USER: $DB_USER # 创建新用户
#      MYSQL_PASSWORD: $DB_USER # 新用户的密码
#    volumes:
#      - /Users/liangliangtoo/myOwnData/mysql/mydir:/mydir
#      - /Users/liangliangtoo/myOwnData/mysql/datadir:/var/lib/mysql
#      - /Users/liangliangtoo/myOwnData/mysql/conf/my.cnf:/etc/my.cnf
#      # 数据库还原目录 可将需要还原的sql文件放在这里
#      - /Users/liangliangtoo/myOwnData/mysql/source:/docker-entrypoint-initdb.d
#    command:
#      # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
#      # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --lower-case-table-names=1 # 设置表名大小写不敏感